(function () {
  const makeBaseline = (entry) => ({
    id: entry.id || entry.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''),
    name: entry.name,
    tag: entry.tag,
    c: entry.c,
    desc: entry.desc,
    useCase: entry.useCase || 'General architecture pattern',
    layers: entry.layers.map((layer) => ({
      t: layer.t,
      p: { ...(layer.p || {}) },
    })),
    sk: (entry.sk || []).map((link) => ({
      f: link.f,
      t: link.t,
    })),
    notes: entry.notes || '',
  });

  const BASELINE_LIBRARY = [
    {
      id: 'resnet-residual-block',
      name: 'ResNet Residual Block',
      tag: 'CNN',
      c: '#10b981',
      desc: 'He et al. 2016 — basic residual block with identity skip',
      useCase: 'Feature extraction and residual learning in CNNs',
      layers: [
        { t: 'Conv2d', p: { in_channels: 64, out_channels: 64, kernel_size: 3, stride: 1, padding: 1 } },
        { t: 'BatchNorm2d', p: { num_features: 64 } },
        { t: 'ReLU', p: {} },
        { t: 'Conv2d', p: { in_channels: 64, out_channels: 64, kernel_size: 3, stride: 1, padding: 1 } },
        { t: 'BatchNorm2d', p: { num_features: 64 } },
      ],
      sk: [{ f: 0, t: 4 }],
      notes: 'Classic residual connection where early feature maps are added back to later activations for stable deep training.',
    },
    {
      id: 'bottleneck-block',
      name: 'Bottleneck Block (ResNet-50)',
      tag: 'CNN',
      c: '#f97316',
      desc: '1×1→3×3→1×1 bottleneck with projection skip',
      useCase: 'Efficient deeper CNN blocks with compact intermediate channels',
      layers: [
        { t: 'Conv2d', p: { in_channels: 256, out_channels: 64, kernel_size: 1, stride: 1, padding: 0 } },
        { t: 'BatchNorm2d', p: { num_features: 64 } },
        { t: 'ReLU', p: {} },
        { t: 'Conv2d', p: { in_channels: 64, out_channels: 64, kernel_size: 3, stride: 1, padding: 1 } },
        { t: 'BatchNorm2d', p: { num_features: 64 } },
        { t: 'ReLU', p: {} },
        { t: 'Conv2d', p: { in_channels: 64, out_channels: 256, kernel_size: 1, stride: 1, padding: 0 } },
        { t: 'BatchNorm2d', p: { num_features: 256 } },
      ],
      sk: [{ f: 0, t: 7 }],
      notes: 'The projection skip keeps channel dimensions compatible while preserving residual learning in higher-capacity CNNs.',
    },
    {
      id: 'pre-norm-transformer',
      name: 'Pre-Norm Transformer (GPT-style)',
      tag: 'NLP',
      c: '#8b5cf6',
      desc: 'Pre-LayerNorm GPT/ViT block with two residual paths',
      useCase: 'Language modeling and transformer stack design',
      layers: [
        { t: 'LayerNorm', p: { normalized_shape: 128 } },
        { t: 'MultiheadAttention', p: { embed_dim: 128, num_heads: 8, dropout: 0.1 } },
        { t: 'Dropout', p: { p: 0.1 } },
        { t: 'LayerNorm', p: { normalized_shape: 128 } },
        { t: 'Linear', p: { in_features: 128, out_features: 512, bias: true } },
        { t: 'GELU', p: {} },
        { t: 'Dropout', p: { p: 0.1 } },
        { t: 'Linear', p: { in_features: 512, out_features: 128, bias: true } },
        { t: 'Dropout', p: { p: 0.1 } },
      ],
      sk: [{ f: 0, t: 3 }, { f: 3, t: 8 }],
      notes: 'Pre-norm residual design is common in large language models because it provides stable gradient flow through deep stacks.',
    },
    {
      id: 'mobilenetv2-inverted-residual',
      name: 'MobileNetV2 Inverted Residual',
      tag: 'Efficient',
      c: '#06b6d4',
      desc: 'Expansion→DW→Projection with linear bottleneck (stride=1)',
      useCase: 'Efficient mobile and edge device CNN architectures',
      layers: [
        { t: 'Conv2d', p: { in_channels: 32, out_channels: 192, kernel_size: 1, stride: 1, padding: 0 } },
        { t: 'BatchNorm2d', p: { num_features: 192 } },
        { t: 'ReLU', p: {} },
        { t: 'DepthwiseSepConv', p: { in_channels: 192, out_channels: 192, kernel_size: 3, padding: 1 } },
        { t: 'BatchNorm2d', p: { num_features: 192 } },
        { t: 'ReLU', p: {} },
        { t: 'Conv2d', p: { in_channels: 192, out_channels: 32, kernel_size: 1, stride: 1, padding: 0 } },
        { t: 'BatchNorm2d', p: { num_features: 32 } },
      ],
      sk: [{ f: 0, t: 7 }],
      notes: 'Inverted residual blocks keep the bottleneck compact and efficient while preserving learned representations with residual flow.',
    },
    {
      id: 'u-net-skip-encoder-stage',
      name: 'U-Net Skip Encoder Stage',
      tag: 'Seg',
      c: '#f59e0b',
      desc: 'U-Net encoder with skip connection saved to decoder',
      useCase: 'Semantic segmentation and dense prediction architectures',
      layers: [
        { t: 'Conv2d', p: { in_channels: 1, out_channels: 64, kernel_size: 3, stride: 1, padding: 1 } },
        { t: 'ReLU', p: {} },
        { t: 'Conv2d', p: { in_channels: 64, out_channels: 64, kernel_size: 3, stride: 1, padding: 1 } },
        { t: 'ReLU', p: {} },
        { t: 'MaxPool2d', p: { kernel_size: 2, stride: 2 } },
        { t: 'Conv2d', p: { in_channels: 64, out_channels: 128, kernel_size: 3, stride: 1, padding: 1 } },
        { t: 'ReLU', p: {} },
      ],
      sk: [{ f: 2, t: 6 }],
      notes: 'U-Net uses skip connections to preserve spatial detail while downsampling for semantic context.',
    },
    {
      id: 'lstm-text-classifier',
      name: 'LSTM Text Classifier',
      tag: 'NLP',
      c: '#ec4899',
      desc: 'Stacked LSTM with embedding for sentiment/classification',
      useCase: 'Sequential text classification and sequence modeling',
      layers: [
        { t: 'Embedding', p: { num_embeddings: 10000, embedding_dim: 128 } },
        { t: 'LSTM', p: { input_size: 128, hidden_size: 256, num_layers: 2, batch_first: true, dropout: 0.3 } },
        { t: 'Dropout', p: { p: 0.5 } },
        { t: 'Linear', p: { in_features: 256, out_features: 64, bias: true } },
        { t: 'ReLU', p: {} },
        { t: 'Linear', p: { in_features: 64, out_features: 2, bias: true } },
        { t: 'Softmax', p: { dim: 1 } },
      ],
      sk: [],
      notes: 'A compact recurrent baseline for classification tasks where sequence order matters.',
    },
  ];

  window.MODEL_BASELINES = BASELINE_LIBRARY.map(makeBaseline);
})();
